apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-deployment
  labels:
    app: feed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feed
  template:
    metadata:
      labels:
        app: feed
    spec:
      containers:
      - name: feed
        image: streamio.azurecr.io/streamio-backend_feed:latest
        env:
          - name: ARTICLEFEEDHOST
            value: 10.0.188.79:3000
          - name: REVIEWFEEDHOST
            value: 10.0.211.234:4001
          - name: PORT
            value: "4005"
        ports:
        - containerPort: 4005
---
apiVersion: v1
kind: Service
metadata:
  name: feed-service
spec:
  selector:
    app: feed
  ports:
    - port: 4005
      targetPort: 4005